before_install:
  - gem install bundler
language: ruby
rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'
  - jruby-19mode
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

